# Generated by Django 4.2.2 on 2023-07-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('breakfast', models.CharField(max_length=250)),
                ('lunch', models.CharField(max_length=250)),
                ('dinner', models.CharField(max_length=250)),
                ('snack', models.CharField(max_length=250)),
                ('hydration', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True, default='', null=True)),
            ],
            options={
                'ordering': ['breakfast'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default='', null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('body_part', models.CharField(max_length=250)),
                ('exercise', models.CharField(max_length=250)),
                ('sets', models.CharField(max_length=250)),
                ('reps', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True, default='', null=True)),
            ],
            options={
                'ordering': ['body_part'],
            },
        ),
    ]
