# Generated by Django 4.2.2 on 2023-07-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_diet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True, default='', null=True)),
                ('diet', models.ManyToManyField(to='main_app.diet')),
                ('workout', models.ManyToManyField(to='main_app.workout')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkoutSerializers',
        ),
    ]
