# Generated by Django 4.2.2 on 2023-07-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
