# Generated by Django 4.2.2 on 2023-07-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_diet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
