# Generated by Django 4.2.2 on 2023-07-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_workout_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='workout',
        ),
    ]
