# Generated by Django 4.2.2 on 2023-07-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_journal_diet_remove_journal_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='user',
        ),
    ]
